name: telco_churn_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - mlflow==2.13.0
      - pandas # <-- Baris ini harus ada
      - scikit-learn # <-- Baris ini harus ada
      - joblib # <-- Baris ini harus ada
